app_name: of-chaos-and-order
app_domain: ofchaosandorder.com
app_server_name: ofchaosandorder.com www.ofchaosandorder.com
app_site_root: /srv/of-chaos-and-order
app_index_file: index.html
nginx_site_name: of-chaos-and-order.conf
nginx_site_path: /etc/nginx/sites-available/{{ nginx_site_name }}
nginx_site_enabled_path: /etc/nginx/sites-enabled/{{ nginx_site_name }}
