#!/bin/bash
. .env

ENVIRONMENT=$1

case $ENVIRONMENT in

dev)
  # .env files often contain sensitive information that should
  # be stored in case of a git clean -f.
  echo "backing up sensitive .env file"
  mkdir -p ~/safe/${IMAGE_NAME} && cp .env ~/safe/${IMAGE_NAME}/env.bk

  # remove any folders generated by the build or runtime process
  echo "removing extraneous files/folders"
  rm -rf dist/
;;

prod)
  # remove any folders generated by the build or runtime process on the production server
  echo "removing extraneous files/folders"
  ssh -t ${PROD_HOST} \
    rm -rf /mnt/msata/build/prod
;;

*)
  echo "please provide one of the following as the first argument: dev, uat, prod."
  exit 1

esac
